# Generated by Django 5.0 on 2023-12-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank='True', max_length=300, null='True', verbose_name='stripe_id'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_payment',
            field=models.PositiveIntegerField(verbose_name='сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(blank='True', null='True', verbose_name='дата оплаты'),
        ),
    ]
