# Generated by Django 4.2 on 2024-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_stripe_id_alter_payment_amount_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(auto_now_add=True, null='True', verbose_name='дата оплаты'),
        ),
    ]
