# Generated by Django 5.0 on 2023-12-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
